param(
	[switch]$SandboxOnly
)

. "$PSScriptRoot\_common.ps1"

# Instance AI local demo: sandbox containers + n8n (DeepSeek).
# Start:  powershell -File demo\start-instance-ai.ps1
# Stop:   powershell -File demo\stop-instance-ai.ps1

Use-Pnpm

# Windows Hyper-V / WinNAT often reserves 5612-5711 (includes default 5678 and runners broker 5679).
# Prefer explicit free ports unless the caller already set them.
if (-not $env:N8N_PORT) { $env:N8N_PORT = '5720' }
if (-not $env:N8N_RUNNERS_BROKER_PORT) { $env:N8N_RUNNERS_BROKER_PORT = '5730' }
if (-not $env:N8N_BASE_URL) { $env:N8N_BASE_URL = "http://localhost:$($env:N8N_PORT)" }
# Re-bind helpers that captured BaseUrl at dot-source time.
$BaseUrl = $env:N8N_BASE_URL.TrimEnd('/')
$Rest = "$BaseUrl/rest"

$env:N8N_USER_FOLDER = $DataDir
$env:N8N_DIAGNOSTICS_ENABLED = 'false'
$env:N8N_SECURE_COOKIE = 'false'
# Local demo: license renew-on-init phones home and can hang for minutes behind corporate/firewall.
$env:N8N_LICENSE_AUTO_RENEW_ENABLED = 'false'
$env:N8N_INSTANCE_AI_SANDBOX_ENABLED = 'true'
$env:N8N_INSTANCE_AI_SANDBOX_PROVIDER = 'n8n-sandbox'
$env:N8N_SANDBOX_SERVICE_URL = 'http://127.0.0.1:18080'
$env:N8N_SANDBOX_SERVICE_API_KEY = 'n8n-sandbox-ci-key'

$statusPath = Join-Path $DemoDir 'l3-status.txt'
$pidPath = Join-Path $DemoDir 'n8n.pid'
$envFile = Join-Path $RepoRoot 'packages\cli\bin\.env'
$composeFile = Join-Path $DemoDir 'sandbox-compose.yml'

function Write-N8nSandboxEnv {
	@(
		'# Generated by demo/start-instance-ai.ps1 — do not edit'
		'N8N_INSTANCE_AI_SANDBOX_PROVIDER=n8n-sandbox'
		'N8N_SANDBOX_SERVICE_URL=http://127.0.0.1:18080'
		'N8N_SANDBOX_SERVICE_API_KEY=n8n-sandbox-ci-key'
		'N8N_INSTANCE_AI_SANDBOX_ENABLED=true'
		''
	) | Set-Content -Path $envFile -Encoding ascii
}

function Test-SandboxHealth {
	try {
		$health = Invoke-RestMethod -Uri "$($env:N8N_SANDBOX_SERVICE_URL)/healthz" -TimeoutSec 5
		return ($health.status -eq 'ok')
	} catch {
		return $false
	}
}

$docker = Get-Command docker -ErrorAction SilentlyContinue
if (-not $docker) {
	throw 'Docker is not installed or not on PATH. Start Docker Desktop first (Engine running).'
}

try {
	docker info --format '{{.ServerVersion}}' | Out-Null
} catch {
	throw 'Docker Engine is not running. Open Docker Desktop and wait for Engine running.'
}

Set-Location $RepoRoot

$sandboxAlready = Test-SandboxHealth
if (-not $sandboxAlready) {
	Write-Host 'Removing leftover testcontainers sandbox (if any)...'
	$ids = docker ps -aq --filter 'name=n8n-svc-' 2>$null
	if ($ids) { docker rm -f $ids | Out-Null }

	Write-Host 'Starting Instance AI sandbox (docker compose, first runner start can take a few minutes)...'
	docker compose -f $composeFile up -d --wait
	if ($LASTEXITCODE -ne 0) {
		throw "Sandbox compose failed (exit $LASTEXITCODE)."
	}
	$deadline = (Get-Date).AddSeconds(90)
	while (-not (Test-SandboxHealth)) {
		if ((Get-Date) -gt $deadline) {
			throw "Sandbox API did not become healthy at $($env:N8N_SANDBOX_SERVICE_URL)/healthz"
		}
		Start-Sleep -Seconds 3
	}
}

Write-N8nSandboxEnv

@(
	"Instance AI started at $(Get-Date -Format o)"
	"Sandbox: $($env:N8N_SANDBOX_SERVICE_URL)"
	'Model: DeepSeek account (deepseek-chat)'
) | Set-Content -Path $statusPath -Encoding utf8

if ($SandboxOnly) {
	Write-Host "Sandbox is up at $($env:N8N_SANDBOX_SERVICE_URL)"
	exit 0
}

Write-Host "Starting n8n at $BaseUrl (data: $DataDir)  port=$($env:N8N_PORT) runnersBroker=$($env:N8N_RUNNERS_BROKER_PORT)"
$launch = @"
`$ErrorActionPreference = 'Stop'
`$env:N8N_USER_FOLDER = '$DataDir'
`$env:N8N_PORT = '$($env:N8N_PORT)'
`$env:N8N_RUNNERS_BROKER_PORT = '$($env:N8N_RUNNERS_BROKER_PORT)'
`$env:N8N_DIAGNOSTICS_ENABLED = 'false'
`$env:N8N_SECURE_COOKIE = 'false'
`$env:N8N_LICENSE_AUTO_RENEW_ENABLED = 'false'
`$env:N8N_INSTANCE_AI_SANDBOX_ENABLED = 'true'
`$env:N8N_INSTANCE_AI_SANDBOX_PROVIDER = 'n8n-sandbox'
`$env:N8N_SANDBOX_SERVICE_URL = 'http://127.0.0.1:18080'
`$env:N8N_SANDBOX_SERVICE_API_KEY = 'n8n-sandbox-ci-key'
`$env:N8N_ENABLED_MODULES = 'agents'
Set-Location '$RepoRoot'
corepack pnpm start
"@
$n8n = Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', $launch) -PassThru -WindowStyle Minimized
$n8n.Id | Set-Content -Path $pidPath -Encoding ascii
Write-Host "n8n pid $($n8n.Id) (saved $pidPath)"

# Cold start with agents module can exceed 3 minutes on this machine.
Wait-N8n -Seconds 360
Initialize-Owner

$creds = Get-Payload (Invoke-N8nJson -Method GET -Url "$Rest/credentials")
$deepseek = @($creds) | Where-Object { $_.type -eq 'deepSeekApi' } | Select-Object -First 1
if (-not $deepseek) {
	Write-Host 'No DeepSeek credential found. Create one in the UI, then pick it in Instance AI settings.'
	exit 0
}

$detail = Get-Payload (Invoke-N8nJson -Method GET -Url "$Rest/credentials/$($deepseek.id)?includeData=true")
$apiKey = $detail.data.apiKey
if ([string]::IsNullOrWhiteSpace($apiKey)) {
	throw 'DeepSeek credential has no apiKey. Re-save it in the UI and re-run this script.'
}
Invoke-N8nJson -Method PUT -Url "$Rest/instance-ai/settings" -Body @{
	modelName       = 'deepseek-chat'
	modelConnection = @{
		type = 'deepSeekApi'
		data = @{ apiKey = $apiKey }
	}
} | Out-Null

Write-Host "Wired Instance AI to '$($deepseek.name)' / deepseek-chat"
Write-Host "Open $BaseUrl   login: $OwnerEmail"
Write-Host 'Stop with: powershell -File demo\stop-instance-ai.ps1'
